name: hello-php by PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: インストールパッケージ
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y php-cli php-mbstring

    - name: 実行 hello-php
      run: php hello-php.php
